highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://trappmartin.github.io
author: Martin Trapp

baseurl: /
title: Jin Li's Personal Webpage
name: Jin Li
email: li.jin[at]siat.ac.cn
email_full: mailto:jinli[at]polyu.edu.hk
website: https://happyjin.github.io/
website_full: https://happyjin.github.io
github: happyjin
GoogleScholar: https://scholar.google.com/citations?user=WBoT7G4AAAAJ&hl=en
#twitter: martin_trapp
#tel: +44 0000 000000
#tel_full: tel:+440000000000
google_maps: 'https://www.google.com/maps/place/Hong+Kong/@22.3531176,113.847485,10z/data=!3m1!4b1!4m5!3m4!1s0x3403e2eda332980f:0xf08ab3badbeac97c!8m2!3d22.3193039!4d114.1693611?hl=en'
#address: Freyung 6/6
#postcode: 1010
city: Hong Kong
#country: China

# needed for travis-ci build
exclude: [vendor]

theme: jekyll-theme-cayman
